### ISSUE TITLE
I wrote typescript types and was wondering if you could review

### ISSUE THREAD

**Issue by Bachmann1234** [stephan83/babar#15]
Howdy! Forgive me if this is not the appropriate venue for this.

I recently used this package in a small toy project 
https://github.com/Bachmann1234/adventOfCodeDifficultyCurve

The project is in typescript so I wrote up some types. I decided it would be worth adding these to the grand mass of types
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49981

I was hoping you would have a few minutes to look over that and see if the type annotations match what you would expect. No pressure, the maintainers of the DefinitelyTyped repo will review it eventually. I just figured as the original author of the module you would be a great fit to look them over.

**Comment by utix** [comment]
Thanks, I have reviewed your PR

**Comment by Bachmann1234** [comment]
Thanks for the review! Would you like me to close this now or when the pr over there merges?

**Comment by utix** [comment]
Let's wait for the merge

**Comment by Bachmann1234** [comment]
This is merged. There was one minor change since you reviewed... but not in the types. Just how the module was exported.
