### ISSUE TITLE
Feature Request: option for fixed y-axis limits

### ISSUE THREAD

**Issue by lennym** [stephan83/babar#4]
Hi - raising an issue first to get an idea of how actively maintained this repo is since it hasn't been touched in a while, but happy to PR the work to implement.

Anyway... I'd like to be able to fix the y-axis limits of charts, in particular at zero to avoid truncation, but also at the top end. Mostly because I have a use case that outputs a series of charts for comparison, and having different y-axes on each makes that difficult.

Let me know if you'd like me to PR this change.

Thanks.

**Comment by stephan83** [comment]
Sorry about the delay, the PR is merged and released in v0.1.0

**Comment by lennym** [comment]
Thanks a lot. And thanks to @dariomannu for doing the work.
